### ISSUE TITLE
Fingerprints cannot be added, because of Error Message

### ISSUE THREAD

**Issue by Juli76911** [LineageOS/android_kernel_xiaomi_sdm845#9]
Ich upgraded my lineageos from latest december build total 24-1-2019 build anderen i noticed that i cannot add new fingerprints. A Pop-up Message ist displayed, that Thema registration of the fingerprint cannot be finished. Is this a bug or do I have a Problem with my Phone? Thanksgiving.

**Comment by f1ras** [comment]
You have to remove all fingerprints in miui and also remove find my phone in miui and then everything should work just fine ;) had the same problem before
